# Generated by Django 4.2.6 on 2023-11-25 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
